deployment:
  staging:
    branch: master
    codedeploy:
      appname-1234:
        application_root: /
        region: us-east-2
        revision_location:
          revision_type: S3
          s3_location:
            bucket: my-bucket
            key_pattern: demo-master-
        deployment_group: my-deployment-group